/* Titan Access helper DLL -- NVDA controller server.
 *
 * Hosts the NvdaController RPC server (see nvdaController.idl) so unmodified
 * nvdaControllerClient*.dll callers drive Titan Access like they would NVDA.
 * The Python side (titan_access/nvda_controller_server.py) loads this DLL,
 * hands us three callbacks, and calls TitanAccessHelper_start/stop. We own all
 * the RPC plumbing; Python never touches rpcrt4.
 *
 * The endpoint MUST equal what the client computes:
 *     "NvdaCtlr." + "<sessionId>.<desktopName>"     over the ncalrpc protseq
 * (see NVDA generateDesktopSpecificNamespace + rpcSrv.cpp). Build instructions
 * are in build.bat / README.md.
 */

#ifndef _WIN32_WINNT
#define _WIN32_WINNT 0x0602   /* RpcServerRegisterIf3 (Win8+) + RPC_QUERY_CLIENT_PID */
#endif

#include <windows.h>
#include <sddl.h>
#include <rpc.h>
#include <stdio.h>
#include "nvdaController.h"   /* generated by MIDL from nvdaController.idl */

#pragma comment(lib, "rpcrt4.lib")
#pragma comment(lib, "advapi32.lib")
#pragma comment(lib, "user32.lib")

/* Callback types handed to us from Python (stdcall to match ctypes WINFUNCTYPE). */
typedef void (__stdcall *TA_SpeakProc)(const wchar_t* text);
typedef void (__stdcall *TA_VoidProc)(void);
typedef void (__stdcall *TA_BrailleProc)(const wchar_t* message);

static TA_SpeakProc   g_onSpeak   = NULL;
static TA_VoidProc    g_onCancel  = NULL;
static TA_BrailleProc g_onBraille = NULL;
static int            g_running   = 0;
static volatile unsigned long g_lastClientPid = 0;

/* Record the PID of the process making the current RPC call, so Titan Access
 * can play its "in a controller app" earcons. Best-effort: leaves the last
 * value untouched if the query fails. */
static void rememberClientPid(void)
{
    RPC_CALL_ATTRIBUTES_V2_W attrs;
    memset(&attrs, 0, sizeof(attrs));
    attrs.Version = RPC_CALL_ATTRIBUTES_VERSION;
    attrs.Flags = RPC_QUERY_CLIENT_PID;
    if (RpcServerInqCallAttributesW(NULL, &attrs) == RPC_S_OK) {
        g_lastClientPid = (unsigned long)(ULONG_PTR)attrs.ClientPID;
    }
}

/* ----- RPC manager routines (called by the generated server stub) --------- */
error_status_t nvdaController_testIfRunning(void)
{
    rememberClientPid();
    return 0;  /* RPC_S_OK -> client sees "a controller (NVDA) is running" */
}

error_status_t nvdaController_speakText(const wchar_t* text)
{
    rememberClientPid();
    if (g_onSpeak && text) g_onSpeak(text);
    return 0;
}

error_status_t nvdaController_cancelSpeech(void)
{
    rememberClientPid();
    if (g_onCancel) g_onCancel();
    return 0;
}

error_status_t nvdaController_brailleMessage(const wchar_t* message)
{
    rememberClientPid();
    if (g_onBraille && message) g_onBraille(message);
    return 0;
}

__declspec(dllexport) unsigned long __stdcall TitanAccessHelper_lastClientPid(void)
{
    return g_lastClientPid;
}

/* ----- endpoint construction (must match the client) ---------------------- */
static void buildEndpoint(wchar_t* out, size_t cch)
{
    DWORD sessionId = 0;
    wchar_t deskName[64];
    HDESK hDesk;

    deskName[0] = L'\0';
    ProcessIdToSessionId(GetCurrentProcessId(), &sessionId);
    hDesk = GetThreadDesktop(GetCurrentThreadId());
    if (hDesk) {
        DWORD needed = 0;
        GetUserObjectInformationW(hDesk, UOI_NAME, deskName,
                                  (DWORD)sizeof(deskName), &needed);
    }
    if (deskName[0] == L'\0')
        wcscpy_s(deskName, 64, L"Default");
    /* "NvdaCtlr." + "<sessionId>.<desktopName>" */
    _snwprintf_s(out, cch, _TRUNCATE, L"NvdaCtlr.%u.%s", sessionId, deskName);
}

/* ----- exported lifecycle ------------------------------------------------- */
__declspec(dllexport) int __stdcall TitanAccessHelper_start(
        TA_SpeakProc onSpeak, TA_VoidProc onCancel, TA_BrailleProc onBraille)
{
    RPC_STATUS status;
    PSECURITY_DESCRIPTOR psd = NULL;
    wchar_t endpoint[160];

    if (g_running)
        return 0;

    g_onSpeak   = onSpeak;
    g_onCancel  = onCancel;
    g_onBraille = onBraille;

    /* DACL: World + AppContainer, generic-all. SACL: a LOW mandatory label with
     * no-execute-up cleared, so clients running at LOW integrity (sandboxed /
     * many 32-bit apps, browser & game child processes) can reach us too --
     * without this they are blocked from a medium-integrity endpoint. Mirrors
     * the access NVDA grants. */
    if (!ConvertStringSecurityDescriptorToSecurityDescriptorW(
            L"D:(A;;GA;;;WD)(A;;GA;;;AC)S:(ML;;NW;;;LW)",
            SDDL_REVISION_1, &psd, NULL)) {
        psd = NULL;  /* fall back to a default DACL */
    }

    buildEndpoint(endpoint, 160);

    status = RpcServerUseProtseqEpW((RPC_WSTR)L"ncalrpc",
                                    RPC_C_PROTSEQ_MAX_REQS_DEFAULT,
                                    (RPC_WSTR)endpoint, psd);
    /* RPC_S_DUPLICATE_ENDPOINT (real NVDA already there) is not fatal here. */
    if (status != RPC_S_OK && status != RPC_S_DUPLICATE_ENDPOINT) {
        if (psd) LocalFree(psd);
        return (int)status;
    }

    /* Register with the security descriptor applied to the interface itself
     * (RpcServerRegisterIf3, Win8+), exactly as NVDA does, so low-IL / 32-bit
     * clients are admitted. */
    status = RpcServerRegisterIf3(
        NvdaController_v1_0_s_ifspec, NULL, NULL,
        RPC_IF_AUTOLISTEN | RPC_IF_ALLOW_CALLBACKS_WITH_NO_AUTH,
        RPC_C_LISTEN_MAX_CALLS_DEFAULT, (unsigned)-1, NULL, psd);

    if (psd) LocalFree(psd);

    if (status != RPC_S_OK)
        return (int)status;

    g_running = 1;
    return 0;
}

__declspec(dllexport) void __stdcall TitanAccessHelper_stop(void)
{
    if (!g_running)
        return;
    RpcServerUnregisterIf(NvdaController_v1_0_s_ifspec, NULL, 1);
    g_onSpeak = NULL;
    g_onCancel = NULL;
    g_onBraille = NULL;
    g_running = 0;
}

/* MIDL needs these allocator hooks for [string] parameters. */
void* __RPC_USER midl_user_allocate(size_t size) { return malloc(size); }
void  __RPC_USER midl_user_free(void* p) { free(p); }

BOOL WINAPI DllMain(HINSTANCE h, DWORD reason, LPVOID reserved)
{
    (void)h; (void)reserved;
    if (reason == DLL_PROCESS_DETACH)
        TitanAccessHelper_stop();
    return TRUE;
}
